/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-11-19 16:50:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.mvcormdata.entity.Books;

public final class displayBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mvcormdata.entity.Books");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Books List</title>\r\n");
      out.write("\r\n");
      out.write("<!-- INTERNAL CSS -->\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        background: #f4f6ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* HEADER */\r\n");
      out.write("    header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background: #0b5ed7;\r\n");
      out.write("        padding: 15px 50px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        z-index: 100;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header h2 {\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        margin-left: 18px;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a:hover {\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    /* TABLE DESIGN */\r\n");
      out.write("    h3 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        color: #0b5ed7;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        box-shadow: 0 4px 20px rgba(0,0,0,0.08);\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        background: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th {\r\n");
      out.write("        background: #0b5ed7;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table, th, td {\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    td, th {\r\n");
      out.write("        padding: 14px 15px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Zebra effect */\r\n");
      out.write("    tr:nth-child(even) {\r\n");
      out.write("        background-color: #f8f9ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Hover effect */\r\n");
      out.write("    tr:hover {\r\n");
      out.write("        background-color: #ffeaa7 !important;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transform: scale(1.01);\r\n");
      out.write("        transition: 0.25s ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* MESSAGE */\r\n");
      out.write("    .no-data {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin: 60px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        color: #666;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- HEADER -->\r\n");
      out.write("<header>\r\n");
      out.write("    <h2>My Application</h2>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"addBook\">Add New Book</a>\r\n");
      out.write("        <a href=\"login\">Login</a>\r\n");
      out.write("        <a href=\"#\">Contact</a>\r\n");
      out.write("        <a href=\"book\">Book</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Books> listOfBook = (List<Books>) request.getAttribute("booksDetails");
	String path=request.getContextPath();

    if (listOfBook == null || listOfBook.isEmpty()) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p class=\"no-data\">No books found.</p>\r\n");
      out.write("\r\n");

    } else {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>List of Books</h3>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>Book ID</th>\r\n");
      out.write("        <th>Name</th>\r\n");
      out.write("        <th>Author</th>\r\n");
      out.write("        <th>Description</th>\r\n");
      out.write("        <th>Price</th>\r\n");
      out.write("        <th>Update</th>\r\n");
      out.write("        <th>Delete</th>\r\n");
      out.write("        \r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("    ");

        for (Books book : listOfBook) {
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td>");
      out.print( book.getBookId() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( book.getBookName() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( book.getBookAuthor() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( book.getBookDescription() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( book.getBookPrice() );
      out.write("</td>\r\n");
      out.write("        <td><a href=\"");
      out.print(path );
      out.write("book/update/");
      out.print(book.getBookId() );
      out.write("\">Update</a></td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"");
      out.print(path );
      out.write("/book/delete/");
      out.print(book.getBookId() );
      out.write("\">Delete</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
